name: new_flutter_inbrain
description: Inbrain surveys for Android & iOS
version: 1.0.3
homepage: https://github.com/Maciejj1/new_flutter_inbrain

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.itlight.new_flutter_inbrain
        pluginClass: FlutterInbrainPlugin
      ios:
        pluginClass: FlutterInbrainPlugin

  
